language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests.test_example
  - coverage run test_QA_Assignment.py
  
after_success:
  - coveralls
