language: python
python:
  - "3.9"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests.test_example
  - python ./test_QA_Assignment.py
